server:
  port: 1110
#  port: ${random.int[1110,1119]}
#服务检查配置
check:
  configList:
      #服务名称
    - serverName: test1
      #cron表达式
      cron: 0/1 * * * * ?
      #cron: 0 0/1 * * * ?  #每分钟检查一次
      #启动脚本位置
      scriptLocation: /opt/restartApp.sh
      #验证的位置
      checkUrl: https://v2.jinrishici.com/one.svg
      #服务名称
    - serverName: test2
      #cron表达式
      cron: 0/1 * * * * ?
      #cron: 0 0/1 * * * ?  #每分钟检查一次
      #启动脚本位置
      scriptLocation: /opt/restartApp.sh
      #验证的位置
      checkUrl: https://localhost:${server.port}
