server:
  port: ${random.int[1110,1119]}
#服务检查配置
check:
  configList:
      #服务名称
    - serverName: gate
      #cron表达式
      cron: 0/1 * * * * ?
#      cron: 0 0/1 * * * ?  #每分钟检查一次
      #启动脚本位置
      scriptLocation: /opt/restartApp.sh
      #验证的位置
      checkUrl: http://127.0.0.1:8080/test
