version: '3'
services:
#  jar:
#    build:
#      context: ""
#      dockerfile: ./Dockerfile
#    image: deilgate:latest
#    container_name: deilgate
#    volumes:
#      - ./logs:/opt
#      - /etc/localtime:/etc/localtime
#    command: [
#               "--server.port=8089",
#               "--spring.profiles.active=dev",
#               "-Djasypt.encryptor.password=password"
#    ]
#    ports:
#      - "8089:8089"
#    environment:
#      RUN_MODEL: --spring.profiles.active=dev
#    deploy:
#      replicas: 1
#      update_config:
#        delay: 30s
#      restart_policy:
#        condition: always
#      resources:
#        limits:
#          memory: 256M


  jar:
      build:
        context: ""
        dockerfile: ./Dockerfile
      image: deilgate:latest
      container_name: deilgate
      ports:
        - "8089:8089"
      environment:
        NETWORK: host
        JVM_OPTS: -server -Xmx512M -Xms512M -XX:MaxMetaspaceSize=256M -XX:CompressedClassSpaceSize=50M -XX:ReservedCodeCacheSize=240M -XX:MaxDirectMemorySize=400M
      logging:
        driver: "json-file"
        options:
          max-size: "10m"
          max-file: "1"
      volumes:
        - "./logs/deilgate:/root/logs"
        - "./logs/deilgate:/app-logs"
      command: [
        "--server.port=8858",
        "--logging.file.path=/app-logs"
      ]
#      restart: always
      network_mode: "host"

# networks:
#   host:
