server:
#  port: ${random.int[8095,8099]}
  port: 8090
deil:
  threadpool:
      enabled: false
      corePoolSize: 4
      maxPoolSize: 10
#      keep-alive-seconds:
#      queueCapacity:
#      threadNamePrefix: PropertiesTest
#      keepAliveSeconds:
#      allowtCoreThreadTimeOut:
#      waitForTasksToCompleteOnShutdown:
#      awaitTerminationSeconds:
#      policys:

spring:
  profiles:
    active: dev
  application:
    name: blingbling
  quartz:
    properties:
      org: